name: Report Build Status

on:
  pull_request:
    branches:
      - develop
    types:
      - ready_for_review
      - synchronize

jobs:
  report-build-status:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.ready_for_review }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.x

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Install
        run: pnpm install

      - name: Tests
        run: pnpm run test:coverage

      - name: Build
        run: pnpm run build
